name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: No duplicate bug report
      description: In case you found a duplicate, add your comments under the already existing issue.
      options:
        - label: I have checked that this bug has not been reported yet
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: What steps should we take to reproduce the bug?
      placeholder: |
        1. Go to this page...
        2. Click this button...
        3. Go grab a coffee...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: visuals
    attributes:
      label: Visuals
      description: Add any visuals that might help to describe the issue
      placeholder: Show us what you see!
    validations:
      required: false
